spring.application.name=job-api-chronos
# Expose the health and info endpoints to the web
management.endpoints.web.exposure.include=health,info
# Show detailed database and disk space health
management.endpoint.health.show-details=always

jwt.secret=${FIN_JWT_SECRET}
# Expiration in milliseconds (e.g., 1 day)
jwt.expiration=86400000
server.port=8082
# 1. The PostgreSQL Connection Coordinates
spring.datasource.url=jdbc:postgresql://localhost:5432/chronos_db
spring.datasource.username=postgres
spring.datasource.password=${FIN_DB_PASSWORD}

# 2. Hibernate Settings (The auto-builder)
# "update" means Spring will automatically create or update your tables based on your Java models
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# 3. (Optional) Show the SQL in your console to verify it's working
spring.jpa.show-sql=true